# Generated by Django 4.1.1 on 2023-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
